service: reviews
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4003

provider:
  name: aws
  runtime: nodejs10.x

functions:
  graphql:
    handler: graphql.handler
    events:
      - http:
          method: post
          path: graphql
  playground:
    handler: playground.handler
    events:
      - http:
          method: get
          path: playground
